const TYPES = { POWER: 'Power', SPEED: 'Speed', TECH: 'Tech' };
const WEAKNESS = { VERY_WEAK: 2, WEAK: 1, NEUTRAL: 0, RESIST: -1, VERY_RESISTANT: -2 };

export const monsters = [
  {
    id: 2,
    name: 'Bnahabra',
    genus: 'Nepteron',
    type: TYPES.TECH,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.RESIST,
      sleep: WEAKNESS.VERY_WEAK,
      blast: WEAKNESS.VERY_WEAK,
      bleed: WEAKNESS.VERY_WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.WEAK,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.WEAK,
      thunder: WEAKNESS.NEUTRAL,
      ice: WEAKNESS.WEAK,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        blunt: true,
        pierce: true,
      },
    ],
    tips: '',
    enraged: null,
  },
  {
    id: 3,
    name: 'Velociprey',
    genus: 'Bird Wyvern',
    type: TYPES.SPEED,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.VERY_WEAK,
      sleep: WEAKNESS.VERY_WEAK,
      blast: WEAKNESS.VERY_WEAK,
      bleed: WEAKNESS.VERY_WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.WEAK,
      water: WEAKNESS.NEUTRAL,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.VERY_WEAK,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        blunt: true,
        pierce: true,
      },
    ],
    tips: '',
    enraged: null,
  },
  {
    id: 4,
    name: 'Velocidrome',
    genus: 'Bird Wyvern',
    type: TYPES.SPEED,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.VERY_WEAK,
      bleed: WEAKNESS.VERY_WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.WEAK,
      water: WEAKNESS.NEUTRAL,
      thunder: WEAKNESS.NEUTRAL,
      ice: WEAKNESS.VERY_WEAK,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        blunt: true,
        pierce: true,
      },
      {
        name: 'Head',
        slash: false,
        blunt: false,
        pierce: true,
      },
      {
        name: 'Torso',
        slash: true,
        blunt: false,
        pierce: false,
      },
    ],
    tips: '',
    enraged: null,
  },
  {
    id: 5,
    name: 'Yian Kut-Ku',
    genus: 'Bird Wyvern',
    type: TYPES.TECH,
    element: 'Fire',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.RESIST,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.RESIST,
      water: WEAKNESS.NEUTRAL,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.VERY_WEAK,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        blunt: true,
        pierce: true,
      },
      {
        name: 'Head',
        slash: false,
        blunt: true,
        pierce: false,
      },
      {
        name: 'Wings',
        slash: false,
        blunt: false,
        pierce: true,
      },
      {
        name: 'Tail',
        slash: true,
        blunt: false,
        pierce: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.SPEED,
    },
  },
  {
    id: 6,
    name: 'Feral Yian Kut-Ku',
    genus: 'Bird Wyvern',
    type: TYPES.TECH,
    element: 'Fire',
    ailments: {
      poison: WEAKNESS.RESIST,
      burn: WEAKNESS.RESIST,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_RESISTANT,
      water: WEAKNESS.RESIST,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.VERY_WEAK,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Wings',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.SPEED,
    },
  },
  {
    id: 1770985092774,
    name: 'Gypceros',
    genus: 'Bird Wyvern',
    type: TYPES.POWER,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.RESIST,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.RESIST,
      blind: WEAKNESS.RESIST,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.RESIST,
      thunder: WEAKNESS.VERY_RESISTANT,
      ice: WEAKNESS.WEAK,
      dragon: WEAKNESS.NEUTRAL,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Stomach',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770987230390,
    name: 'Purple Gypceros',
    genus: 'Bird Wyvern',
    type: TYPES.POWER,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.VERY_RESISTANT,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.RESIST,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.RESIST,
      blind: WEAKNESS.RESIST,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.WEAK,
      thunder: WEAKNESS.VERY_RESISTANT,
      ice: WEAKNESS.WEAK,
      dragon: WEAKNESS.NEUTRAL,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Stomach',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770987351285,
    name: 'Chatacabra',
    genus: 'Amphibian',
    type: TYPES.POWER,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.NEUTRAL,
      water: WEAKNESS.RESIST,
      thunder: WEAKNESS.VERY_WEAK,
      ice: WEAKNESS.WEAK,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Torso',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Left Arm',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Right Arm',
        slash: false,
        pierce: false,
        blunt: true,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770987619138,
    name: 'Feral Chatacabra',
    genus: 'Amphibian',
    type: TYPES.POWER,
    element: 'Thunder',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.VERY_RESISTANT,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.RESIST,
      bleed: WEAKNESS.RESIST,
      blind: WEAKNESS.VERY_RESISTANT,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.NEUTRAL,
      water: WEAKNESS.WEAK,
      thunder: WEAKNESS.RESIST,
      ice: WEAKNESS.VERY_WEAK,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Torso',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Left Arm',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Right Arm',
        slash: false,
        pierce: false,
        blunt: true,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770987790486,
    name: 'Nerscylla',
    genus: 'Temnoceran',
    type: TYPES.TECH,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.RESIST,
      sleep: WEAKNESS.VERY_RESISTANT,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.RESIST,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.NEUTRAL,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Legs',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Needle',
        slash: false,
        pierce: true,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.SPEED,
    },
  },
  {
    id: 1770987918775,
    name: 'Anjanath',
    genus: 'Brute Wyvern',
    type: TYPES.POWER,
    element: 'Fire',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.RESIST,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.RESIST,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_RESISTANT,
      water: WEAKNESS.VERY_WEAK,
      thunder: WEAKNESS.NEUTRAL,
      ice: WEAKNESS.WEAK,
      dragon: WEAKNESS.VERY_RESISTANT,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Legs',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770988079713,
    name: 'Plesioth',
    genus: 'Piscine Wyvern',
    type: TYPES.SPEED,
    element: 'Water',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.VERY_WEAK,
      sleep: WEAKNESS.RESIST,
      blast: WEAKNESS.RESIST,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.WEAK,
      water: WEAKNESS.VERY_RESISTANT,
      thunder: WEAKNESS.VERY_WEAK,
      ice: WEAKNESS.NEUTRAL,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Back',
        slash: false,
        pierce: true,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.POWER,
    },
  },
  {
    id: 1770988209074,
    name: 'Green Plesioth',
    genus: 'Piscine Wyvern',
    type: TYPES.SPEED,
    element: 'Water',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.VERY_WEAK,
      sleep: WEAKNESS.RESIST,
      blast: WEAKNESS.RESIST,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.WEAK,
      water: WEAKNESS.VERY_RESISTANT,
      thunder: WEAKNESS.VERY_WEAK,
      ice: WEAKNESS.RESIST,
      dragon: WEAKNESS.NEUTRAL,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Back',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770988347030,
    name: 'Ludroth',
    genus: 'Leviathan',
    type: TYPES.POWER,
    element: 'Water',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.VERY_WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.VERY_WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.WEAK,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.RESIST,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.NEUTRAL,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
    ],
    tips: '',
    enraged: null,
  },
  {
    id: 1770988408050,
    name: 'Royal Ludroth',
    genus: 'Leviathan',
    type: TYPES.POWER,
    element: 'Water',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.VERY_WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.VERY_RESISTANT,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.NEUTRAL,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Stomach',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770988571373,
    name: 'Tobi-Kadachi',
    genus: 'Fanged Wyvern',
    type: TYPES.SPEED,
    element: 'Thunder',
    ailments: {
      poison: WEAKNESS.VERY_WEAK,
      burn: WEAKNESS.WEAK,
      paralysis: WEAKNESS.RESIST,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.WEAK,
      water: WEAKNESS.VERY_WEAK,
      thunder: WEAKNESS.VERY_RESISTANT,
      ice: WEAKNESS.NEUTRAL,
      dragon: WEAKNESS.RESIST,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Legs',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: false,
        pierce: false,
        blunt: true,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.TECH,
    },
  },
  {
    id: 1770988679214,
    name: 'Paolumu',
    genus: 'Flying Wyvern',
    type: TYPES.TECH,
    element: 'Normal',
    ailments: {
      poison: WEAKNESS.WEAK,
      burn: WEAKNESS.VERY_WEAK,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.VERY_WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.VERY_WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_WEAK,
      water: WEAKNESS.VERY_RESISTANT,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.RESIST,
      dragon: WEAKNESS.NEUTRAL,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Torso',
        slash: true,
        pierce: false,
        blunt: false,
      },
      {
        name: 'Neck',
        slash: false,
        pierce: true,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.SPEED,
    },
  },
  {
    id: 1770988815106,
    name: 'Rathian',
    genus: '',
    type: TYPES.SPEED,
    element: 'Fire',
    ailments: {
      poison: WEAKNESS.RESIST,
      burn: WEAKNESS.RESIST,
      paralysis: WEAKNESS.WEAK,
      sleep: WEAKNESS.WEAK,
      blast: WEAKNESS.WEAK,
      bleed: WEAKNESS.WEAK,
      blind: WEAKNESS.WEAK,
    },
    elements: {
      normal: WEAKNESS.NEUTRAL,
      fire: WEAKNESS.VERY_RESISTANT,
      water: WEAKNESS.NEUTRAL,
      thunder: WEAKNESS.WEAK,
      ice: WEAKNESS.RESIST,
      dragon: WEAKNESS.VERY_WEAK,
    },
    parts: [
      {
        name: 'Main Body',
        slash: true,
        pierce: true,
        blunt: true,
      },
      {
        name: 'Head',
        slash: false,
        pierce: false,
        blunt: true,
      },
      {
        name: 'Wings',
        slash: false,
        pierce: true,
        blunt: false,
      },
      {
        name: 'Tail',
        slash: true,
        pierce: false,
        blunt: false,
      },
    ],
    tips: '',
    enraged: {
      trigger: 'Hp < 50%',
      type: TYPES.POWER,
    },
  },
];
